// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMe4uUAWPxXNo6YC2s3nQamEUf2F7y9_w',
    appId: '1:588405158371:web:88375567743b971ca1b0d6',
    messagingSenderId: '588405158371',
    projectId: 'agriguide-21792',
    authDomain: 'agriguide-21792.firebaseapp.com',
    storageBucket: 'agriguide-21792.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rrqgRFBx4JTAD2eiqdt3iXec7CzaOls',
    appId: '1:588405158371:android:2f1b0dda734c8c61a1b0d6',
    messagingSenderId: '588405158371',
    projectId: 'agriguide-21792',
    storageBucket: 'agriguide-21792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfA2sBWk4nwnJObNMr3xxu3nT0TXuvquU',
    appId: '1:588405158371:ios:7161c69adb391f1fa1b0d6',
    messagingSenderId: '588405158371',
    projectId: 'agriguide-21792',
    storageBucket: 'agriguide-21792.firebasestorage.app',
    iosBundleId: 'com.example.agriGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfA2sBWk4nwnJObNMr3xxu3nT0TXuvquU',
    appId: '1:588405158371:ios:7161c69adb391f1fa1b0d6',
    messagingSenderId: '588405158371',
    projectId: 'agriguide-21792',
    storageBucket: 'agriguide-21792.firebasestorage.app',
    iosBundleId: 'com.example.agriGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMe4uUAWPxXNo6YC2s3nQamEUf2F7y9_w',
    appId: '1:588405158371:web:2aed2d995ab8589fa1b0d6',
    messagingSenderId: '588405158371',
    projectId: 'agriguide-21792',
    authDomain: 'agriguide-21792.firebaseapp.com',
    storageBucket: 'agriguide-21792.firebasestorage.app',
  );
}
